{
 "title": "OpenNebula",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Cloud Elements",
   "type": "gauge",
   "description": "Overall number of objects in the OpenNebula cloud",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "opennebula_host_total", "legendFormat": "__auto" },
    { "expr": "opennebula_vm_total", "legendFormat": "__auto" },
    { "expr": "opennebula_datastore_total", "legendFormat": "__auto" },
    {
     "expr": "sum(opennebula_datastore_images{one_datastore_id!=\"2\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Host Memory Usage",
   "type": "timeseries",
   "description": "Overall Memory capacity available and used in the Cloud",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(opennebula_host_mem_maximum_bytes)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(opennebula_host_mem_usage_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VM Status",
   "type": "bargauge",
   "description": "Number of VMs in a given state",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(count(opennebula_vm_state{} == 1))",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "scalar(count(opennebula_vm_state{} == 2))",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "scalar(count(opennebula_vm_state{} == 3))",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "scalar(count(opennebula_vm_state{} == 4 or opennebula_vm_state{} == 5))",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "scalar(count(opennebula_vm_state{} == 8 or opennebula_vm_state{} == 9))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Host States",
   "type": "bargauge",
   "description": "Number of hosts in a given state",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(count(opennebula_host_state{} == 0))",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "scalar(count(opennebula_host_state{} == 3))",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "scalar(count(opennebula_host_state{} == 2))",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "scalar(count(opennebula_host_state{} == 4 or opennebula_host_state{} == 8))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Host CPU Usage",
   "type": "timeseries",
   "description": "Overall CPU capacity available and used in the Cloud",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(opennebula_host_cpu_maximum_ratio)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(opennebula_host_cpu_usage_ratio)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Datastore Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(opennebula_datastore_total_bytes{one_datastore_id!=\"2\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(opennebula_datastore_free_bytes{one_datastore_id!=\"2\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(opennebula_datastore_used_bytes{one_datastore_id!=\"2\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}